### ISSUE TITLE
GrindrPlus and LSPatch

### ISSUE THREAD

**Issue by kogan92** [R0rt1z2/GrindrPlus#10]
Any version newer than v2.1.3 (for v24.2.0) won't work on unrooted Android devices with LSPatch. It crashes immediately, despite the guide.

Device used: S24 Ultra with One UI 6.1 and Android 14

**Comment by oroboros** [comment]
> https://xdaforums.com/t/mod-xposed-grindr-plus.4461857/page-87#post-89528371

Would be more helpful to link directly to the proper post: https://xdaforums.com/t/mod-xposed-grindr-plus.4461857/post-89494144

**Comment by R0rt1z2** [comment]
> > https://xdaforums.com/t/mod-xposed-grindr-plus.4461857/page-87#post-89528371
> 
> Would be more helpful to link directly to the proper post: https://xdaforums.com/t/mod-xposed-grindr-plus.4461857/post-89494144

To be honest, I thought I had linked the post you just sent. I guess I didn't double check before sending the link to this thread.

Anyway, considering this is now resolved (with a workaround), I'll close this issue.

**Comment by kogan92** [comment]
unfortunately, the workaround doesn't work. As a rooted device, the last working version is Grindr v24.2.0 + Grindr Plus v2.1.3 + LSPatch (integrated method).

**Comment by R0rt1z2** [comment]
> unfortunately, the workaround doesn't work. As a rooted device, the last working version is Grindr v24.2.0 + Grindr Plus v2.1.3 + LSPatch (integrated method).

Why are you using LSPatch if your device is rooted?

**Comment by kogan92** [comment]
> > unfortunately, the workaround doesn't work. As a rooted device, the last working version is Grindr v24.2.0 + Grindr Plus v2.1.3 + LSPatch (integrated method).
> 
> Why are you using LSPatch if your device is rooted?

is there then a valid alternative to LSPatch for rooted devices? I use Shizuku and LSPatch to make GrindrPlus working, but now I cannot even refresh the timeline nor log into my account.

**Comment by R0rt1z2** [comment]
> > > unfortunately, the workaround doesn't work. As a rooted device, the last working version is Grindr v24.2.0 + Grindr Plus v2.1.3 + LSPatch (integrated method).
> > 
> > 
> > Why are you using LSPatch if your device is rooted?
> 
> is there then a valid alternative to LSPatch for rooted devices? I use Shizuku and LSPatch to make GrindrPlus working, but now I cannot even refresh the timeline nor log into my account.

Have you actually read the `README.md`? I explicitly state that **LSPatch is not recommended** (nor stable). If you are rooted, **you should be using LSPosed instead**, which is known to work without any issues at all. As for not being able to refresh or log in, if you're using AdAway, whitelist `cdn.cookielaw.org`. If not, Grindr might be undergoing maintenance, as someone else reported the same issue a few hours ago: https://github.com/R0rt1z2/GrindrPlus/issues/12

**Comment by kogan92** [comment]
yes I read the README file nad it says specifically this:

"LSPosed instructions
Root your device:

- There is no specific guide for this, you will have to look it up on your own. LSPosed only supports Magisk and KernelSU
- If you can't root your phone either because you can't unlock the bootloader or another reason, you will have to use LSPatch"

And LSPatch is what I have been us

So you're basically telling me to root my device anyways, right?

**Comment by R0rt1z2** [comment]
> yes I read the README file and it says specifically this:
> 
> "LSPosed instructions Root your device:
> 
>     * There is no specific guide for this, you will have to look it up on your own. LSPosed only supports Magisk and KernelSU
> 
>     * If you can't root your phone either because you can't unlock the bootloader or another reason, you will have to use LSPatch"
> 
> 
> And LSPatch is what I have been using so far on my unrooted s24 ultra
> 
> So you're basically telling me to root my device anyways, right?

I assumed it was already rooted because you said, “_As a rooted device, the last working version is ..._”. Maybe I misunderstood what you meant. In any case, yes, it's preferable to root your device if that's an option for you. I can't really help with LSPatch as I don't use it. As far as I know, @poundross was working on a lot of improvements for LSPatch (which should hopefully fix whatever is going on with it), but I haven't heard about it for a while.

**Comment by kogan92** [comment]
ok, fair enough. Thanks anyways
