### ISSUE TITLE
Grindr crashes after activation of grindrplus

### ISSUE THREAD

**Issue by anonymous992** [R0rt1z2/GrindrPlus#14]
As in the title, the grindr app force close for me after I activated grindrplus

I'm using grindrplus 3.1.5 with grindr 24.9.0 on android 14 with lsposed_mod 1.9.3

**Comment by R0rt1z2** [comment]
Yeah, I've updated the APK (I accidentally uploaded a bad version). Re-download it and check the md5sum: 1806aaa6048fc3b854baa7469b0677d3
