### ISSUE TITLE
Grindr Crashes After August 5, 2024 Security Patch

### ISSUE THREAD

**Issue by JaneGrindr** [R0rt1z2/GrindrPlus#21]
I am writing to report a critical issue with the Grindr app following the Android security patch update to August 5, 2024. Since the update, the app consistently crashes and is no longer functional on my device.

I have tried reinstalling the app, clearing the cache, and restarting my device, but none of these solutions have resolved the problem.

I hope you can address this issue promptly, as it is a valuable tool for many users.

Thank you for your attention to this matter.

**Comment by katzecz** [comment]
Checkout Discord group, you can find more info about it there, as well as modified apk as a workaround.

**Comment by R0rt1z2** [comment]
> _(From the Discord server)_
**New fix for the crashing issue with the august 1 google play system update:**
```shell
adb uninstall com.google.android.art
```

**Comment by DomOfKnight** [comment]
I sure would like to find that Discord server too. Grindr just forced an update for users of 24.8, so now I can't use GrindrPlus at all. I tried 'adb uninstall com.google.android.art' but it says app is not found and thus not uninstalled. I had posted about this in discussions prior to no avail.

**Comment by R0rt1z2** [comment]
It's linked in the README
![imagen](https://github.com/user-attachments/assets/be750b46-9cc8-4064-bb83-53f6c9627061)

**Comment by R0rt1z2** [comment]
Fixed with 3.2.1.
