### ISSUE TITLE
[BUG]: Grindr closes on its own even while connected in Wireless debug using Shizuku and LSPatch

### ISSUE THREAD

**Issue by Emoboy004** [R0rt1z2/GrindrPlus#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i hope Grindr, the app instantly crashes, i tried to reconnect, unistall it, install the base app and patch it, both on local and integrated mode and reinstalled Grindr Plus but with no success

### Steps to reproduce

Simply open the app

### Installation Method

LSPatch

### LSPatch version

0.6

### LSPatch variant

Official

### ROM

OneUI 6.1

### Android Version

14

### Google Play system update date

August 1, 2024

### Security patch date

July 1, 2024

### Grindr version

24.12.0

### GrindrPlus version

v3.2.1-24.12.0

**Comment by Emoboy004** [comment]
Fixed the Grindr version

**Comment by Emoboy004** [comment]
Yea, it works perfectly now
Thanks so much!

Il Ven 20 Set 2024, 13:30 Roger Ortiz ***@***.***> ha scritto:

**Comment by R0rt1z2** [comment]
Great! Closing as completed.
