### ISSUE TITLE
[BUG]: My top songs 

### ISSUE THREAD

**Issue by Rtpda** [R0rt1z2/GrindrPlus#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Hello, not too sure how this works, but does anyone else get this error that when you click to view a profile it opens a black screen that says my top songs? I I have to close the app and go back in again...happens all the time 

### Steps to reproduce

Go to profiles 
Click on any profile 
See the black screen saying my top songs 

### Installation Method

LSPatch

### LSPatch version

0.6(398)

### LSPatch variant

LSPosed_mod

### LSPosed version

1.9.2 (7024)

### ROM

OneUI

### Android Version

14

### Google Play system update date

20/09/24

### Security patch date

12/09/24

### Grindr version

24.12.0

### GrindrPlus version

v3.2.1-24.12.0

**Comment by R0rt1z2** [comment]
Are you using an AdBlocker? If so, try disabling it.

**Comment by Rtpda** [comment]
No, I'm not using an Adblocker

**Comment by R0rt1z2** [comment]
Have you tried using JingMatrix's LSPatch?

**Comment by Rtpda** [comment]
Yes, I tried with JingMatrix's LSPatch and still get the same error. Do you know if there's a way for me to find out if there's an add blocker running on the background?

**Comment by R0rt1z2** [comment]
> Yes, I tried with JingMatrix's LSPatch and still get the same error. Do you know if there's a way for me to find out if there's an add blocker running on the background?

Honestly, I’m not sure what else could be causing the issue if you’re not using any AdBlocker. The problem you described matches cases where users were using tools like AdAway or similar. I’d recommend starting from scratch with a clean installation. You can use GrindrPlus' built-in "export database/config" options to back up your data and import it afterward.

If the issue persists, I’d suggest capturing logs. A quick Google search should provide instructions on how to do this (I'm not gonna do a how-to tutorial, sorry).

**Comment by R0rt1z2** [comment]
Any updates on this? Have you tried the latest versions of the mod?

**Comment by Rtpda** [comment]
Hey, just installed the latest version and the issue still there, no idea why it happens 😟

**Comment by R0rt1z2** [comment]
Fixed on the latest version.
