### ISSUE TITLE
[BUG]: stopped working 

### ISSUE THREAD

**Issue by DjinnDjab** [R0rt1z2/GrindrPlus#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

this has stopped working, no unlimited scrolling etc.

### Steps to reproduce

none needed

### Installation Method

LSPosed

### LSPosed version

1.9.3_mod

### ROM

pixel stock

### Android Version

15, ap41.240823.009

### Google Play system update date

8-1-24

### Security patch date

9-5-24

### Grindr version

24.12 0

### GrindrPlus version

v3.2.1-24.12.0

**Comment by R0rt1z2** [comment]
Switch to JingMatrix's fork. LSPosed_mod is no longer supported, nor is the outdated official LSPosed version.
![image](https://github.com/user-attachments/assets/5fa3961d-e913-49c7-a076-8d2634302385)

**Comment by DjinnDjab** [comment]
wow thanks for the info, I am back in action!!

**Comment by R0rt1z2** [comment]
Does it work now?

**Comment by DjinnDjab** [comment]
actually, after removing 1.9.3_mod and installing 1.10.0 from jingmatrix,
it is not working,  tried rebooting, foreclosing Grindr, the mod settings
are in the app, they just don't appear to be functioning, what's
interesting is gps setter had stopped working as well but that is now
working under 1.10.0
