### ISSUE TITLE
Mod not working 

### ISSUE THREAD

**Issue by Yahoo302** [R0rt1z2/GrindrPlus#3]
Mod is completely not working.
V 3.1.0.
V 24.4.0.
Using Lspatch

Precious version (3.0.0. - 24.3. 1) worked perfectly

**Comment by 0x4bb** [comment]
Yeah. Conversations auto close. Basically can't message anyone.

**Comment by R0rt1z2** [comment]
Known issue. That's why I recommend using LSPosed. As for the conversation issue, we are working on it.

**Comment by Yahoo302** [comment]
> Known issue. That's why I recommend using LSPosed. As for the conversation issue, we are working on it.

Can lsposed be used without root?

**Comment by R0rt1z2** [comment]
> > Known issue. That's why I recommend using LSPosed. As for the conversation issue, we are working on it.
> 
> Can lsposed be used without root?

Unfortunately not. I suggest you use a different APK (use the official one, from Play Store) instead of the one from APKMirror when patching with LSPatch and see if it makes any difference.

**Comment by Yahoo302** [comment]
> > > Known issue. That's why I recommend using LSPosed. As for the conversation issue, we are working on it.
> > 
> > 
> > Can lsposed be used without root?
> 
> Unfortunately not. I suggest you use a different APK (use the official one, from Play Store) instead of the one from APKMirror when patching with LSPatch and see if it makes any difference.

U can embedd a play store downloaded app with grindr plus via Lspatch?

**Comment by 0x4bb** [comment]
> Known issue. That's why I recommend using LSPosed. As for the conversation issue, we are working on it.

Thanks. And thanks for maintaining the mod. <3

**Comment by DjinnDjab** [comment]
it's an issue with lsposed too

**Comment by R0rt1z2** [comment]
> > > > Known issue. That's why I recommend using LSPosed. As for the conversation issue, we are working on it.
> > > 
> > > 
> > > Can lsposed be used without root?
> > 
> > 
> > Unfortunately not. I suggest you use a different APK (use the official one, from Play Store) instead of the one from APKMirror when patching with LSPatch and see if it makes any difference.
> 
> U can embedd a play store downloaded app with grindr plus via Lspatch?

Should be possible. There's a feature called 'Select an installed app' that allows you to choose from among your installed applications.
<p align="center">
  <img src="https://github.com/R0rt1z2/GrindrPlus/assets/39171306/44e7dbbe-945b-4139-9161-174a9f8efa78">
</p>

**Comment by R0rt1z2** [comment]
Please test with the latest version and Grindr 24.4.1.

**Comment by wikimeza** [comment]
Tried with 24.4.0 and 24.4.1 and not working with LsPatch, is it possible to update the Mod for 24.3.1?

**Comment by R0rt1z2** [comment]
https://github.com/R0rt1z2/GrindrPlus/issues/10#issuecomment-2230538229
