### ISSUE TITLE
[BUG]: i can't select a different city from the grindr location changer

### ISSUE THREAD

**Issue by Emoboy004** [R0rt1z2/GrindrPlus#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i choose a city using the grindr location changer, it doesn't show me a way to select it
In the example i already wrote London but nothing
![Screenshot_20241006_015417_Grindr](https://github.com/user-attachments/assets/a66fb9eb-c786-4185-820a-66cb679921c2)

### Steps to reproduce

I simply click the top bar, on the main menu, click the bottom bar on the gps chooser menu, write a city, select it, then select the exact position and then white screen

### Installation Method

LSPatch

### LSPatch version

0.6 (418)

### LSPatch variant

JinxMatrix

### ROM

OneUI 6.1

### Android Version

14

### Google Play system update date

August 1, 2024

### Security patch date

July 1, 2024

### Grindr version

24.12.0 (127593)

### GrindrPlus version

v3.2.1-24.12.0

**Comment by R0rt1z2** [comment]
Expected. Broken with LSPatch.

![image](https://github.com/user-attachments/assets/edb98b54-1add-4511-addd-e2441d3f4cba)
