### ISSUE TITLE
Delivery/Read status is wrong 

### ISSUE THREAD

**Issue by secrj** [R0rt1z2/GrindrPlus#4]
Since at least 2-3 versions, message  delivery status isn't correct. I normally have unlimited. With mod I can see sometimes status going to Read and after a while, or after I leave message window and go back, it has reverted to delivered. Maybe you can fix that (not sure if it is mod issue) or just keep it read, once read status has been reached once for the message?

As always,
Thanks very much for your effort on the plug-in

**Comment by R0rt1z2** [comment]
The last two versions of the mod only prevent others from seeing your "writing" indicator, regardless of whether or not you and the other person have Grindr Unlimited. Other statuses such as delivered and read are handled solely and exclusively by the server.
