### ISSUE TITLE
Current Version v24.1.1 Very Slow laggy

### ISSUE THREAD

**Issue by Doralah** [R0rt1z2/GrindrPlus#8]
Hi is there an update for this cuz the current version is very laggy and sometimes chat aren't sent properly.

**Comment by R0rt1z2** [comment]
I have tried the latest version (with LSPosed) on three different devices, ranging from 2 GB to 8 GB of RAM, and I haven't experienced any lag. If the issue stems from LSPatch, I'm afraid there's nothing I can do about it.
